version: '3'
services:
  postgres:
    container_name: container-postgresdb
    image: postgres
    hostname: postgres
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: TEST_SM
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      -
        type: bind
        source: /home/john/work/postgresql/data
        target: /var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: willems@disroot.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
